#!/bin/sh
export PATH='/opt/usr/sbin:/opt/usr/bin:/opt/sbin:/opt/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin'
export LD_LIBRARY_PATH=/lib:/opt/lib
num=`ps | grep /usr/local/bin/bin/server | grep -v grep | grep -v check | wc -l`
if [ $num -lt 1 ]
then /usr/local/bin/bin/server -l :23 -t 127.0.0.1:8080 -key 123456 -mode fast2 > kcptun.log 2>&1 &
 /usr/local/bin/bin/server -l :24 -t 127.0.0.1:189 -key 123456 -mode fast > kcptun.log 2>&1 &
fi
